from dataclasses import dataclass
from datetime import datetime
from typing import Optional, Dict, Any, List, Literal
from enum import Enum

class SignalSide(Enum):
    LONG = "long"
    SHORT = "short"
    NONE = "none"

@dataclass
class MarketSignal:
    """Represents a trading signal generated by the strategy."""
    side: SignalSide
    entry_price: float
    stop_loss: float
    take_profit: float
    atr: float
    timestamp: datetime
    metadata: Dict[str, Any]

@dataclass
class Position:
    """Represents an active trading position."""
    symbol: str
    side: SignalSide
    contracts: float
    entry_price: float
    unrealized_pnl: float
    leverage: int
    margin_mode: str

@dataclass
class OrderResult:
    """Represents the result of an executed order."""
    order_id: str
    symbol: str
    side: str
    price: float
    amount: float
    status: str
    timestamp: datetime
